# port
server:
  port: ${port:8080}

# scan beans
mybatis:
  type-aliases-package: com.learn.provider_service.entity
  # mapper.xml path
  mapper-locations: classpath:mappers/*Mapper.xml

# database info
spring:
  datasource:
    data-username: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/test?setUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

  #redis config
#  redis:
#    host: localhost
#    port: 6379
  #server id
  application:
    name: firstApplication
